# Generated by Django 3.0 on 2021-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=500)),
                ('TaskCompleted', models.BooleanField(default=False)),
                ('TaskDescription', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
